version: '3.1'

services:
  mongo:
    container_name: lat-db
    image: "mongo:4.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lesautodb
      MONGO_INITDB_ROOT_PASSWORD: lesautodb
    ports:
      - "27017:27017"
    volumes:
      - lat-db-data:/data/db

volumes:
  lat-db-data:
